### ISSUE TITLE
Add pictures to instructions

### ISSUE THREAD

**Issue by DJMcMuffin0** [mrzapp/nextcloud-cookbook#145] opened 2020-02-02 12:40 UTC
It would be great if you could add pictures to the instructions.

For cake making it would be ideal for example. After each step you could take a picture and show the progress and how it should look like as of that point.

**Comment by mrzapp** [comment] 2020-02-29 16:56
Closing as duplicate of #47

**Closed by mrzapp** 2020-02-29 16:56 UTC
