### ISSUE TITLE
Dutch translation is missing in 0.7.1 All labels are in English

### ISSUE THREAD

**Issue by RobRobM** [mrzapp/nextcloud-cookbook#241] opened 2020-06-08 07:57 UTC
All Dutch translations are gone, every label is in English.

Ps. Thanks for all the hard work. I love the Cookbook app!

**Comment by mrzapp** [comment] 2020-06-08 08:05
Dankjewel @RobRobM :)

Transifex, the translation service we're using, should automatically translate strings with every update we do, but since moving to Vue.js, it seems we've run into some trouble.

@christianlupus @sam-19 do you have any ideas?

**Comment by christianlupus** [comment] 2020-06-08 14:11
The translations are still there in the `l10n` folder. So the transifex connection is working fine as far as I can tell. Now I am unsure about the effects of Vue.js on the import/localization.

I just checked the problem on my installation (German by default). On an old installation 0.6.5 everything was ok. On the 0.7.2 I can confirm the texts are mostly all back to English.

I have no experience in Vue.js. How does it work? I just looked (as an example) into [this line](https://github.com/mrzapp/nextcloud-cookbook/blob/13e6ee41f9674d770cda84dd05f109d925d32223/src/components/RecipeEdit.vue#L3) I do not understand at the moment how this is parsed. Is it going to be interpreted as HTML? Seems strange for me, unfortunately. The important part is that the function `t(...)` is evaluated. I fear this is not happening here at the right moment. I fear you need more in-depth knowledge of vue to get there.

**Comment by sam-19** [comment] 2020-06-08 14:23
I think the shortcut I had to take to pass the translation function to Vue may be the cause. This is actually why I wanted someone with experience with the translation engine to check it out first :) However, it's not a big deal to fix (actually a batch find and replace), assuming that is the cause. I will take a look at it and post a pull request later this week, but I will need someone else to test it.

**Comment by hitam4450** [comment] 2020-06-08 16:57
> The translations are still there in the `l10n` folder. So the transifex connection is working fine as far as I can tell. Now I am unsure about the effects of Vue.js on the import/localization.
> 
> I just checked the problem on my installation (German by default). On an old installation 0.6.5 everything was ok. On the 0.7.2 I can confirm the texts are mostly all back to English.
> 
> I have no experience in Vue.js. How does it work? I just looked (as an example) into [this line](https://github.com/mrzapp/nextcloud-cookbook/blob/13e6ee41f9674d770cda84dd05f109d925d32223/src/components/RecipeEdit.vue#L3) I do not understand at the moment how this is parsed. Is it going to be interpreted as HTML? Seems strange for me, unfortunately. The important part is that the function `t(...)` is evaluated. I fear this is not happening here at the right moment. I fear you need more in-depth knowledge of vue to get there.

Same here..... see https://github.com/mrzapp/nextcloud-cookbook/issues/238

**Comment by mrzapp** [comment] 2020-06-13 05:45
@christianlupus @RobRobM @hitam4450 can you guys check if the latest release fixes this for you?

**Comment by RobRobM** [comment] 2020-06-13 09:11
Still in English.

**Comment by sam-19** [comment] 2020-06-13 13:36
In fact, I can only see four translated strings in the Dutch translation file and when viewing the project in Transifex. It's like all the other strings have disappeared somehow. Some previous versions of the translation files have a lot more strings. How do you trigger the source code crawler, @mrzapp, so we could possibly regain the old translations? The actual files can be rolled back if needed, but I wonder if they are really lost to the Transifex engine?

**Comment by christianlupus** [comment] 2020-06-14 08:16
I just looked into it a bit.

First information: The crawler comes by every night, scans for translatable strings and pushes a commit to the repository if new strings/translations were found. So we have to wait until the @nextcloud-bot comes back and rereads and pushes updates.

Second, I found the problem was introduced in [this commit](https://github.com/mrzapp/nextcloud-cookbook/commit/0f398f1bd6a7d155871c06f94c234f5b833ab8d8). Most of the translations were removed there. However, there are still around 60 translations per language in the transifex system. So, the translations seem not (yet?) be removed.

My personal assumption is that the crawling bot requires the js files to be present. Some research in this repo later, it seems that these are generated from the `*.vue` files upon release preparation. Is this right, @sam-19 @mrzapp?
I know that the calendar from the core team uses both transifex and vue. I will look into their solution  and see if I can get something from them.

Unfortunately, we will not have any useful translation until the next release.

**Comment by christianlupus** [comment] 2020-06-14 10:32
I just opened [this issue](https://github.com/nextcloud/docker-ci/issues/228). I am unsure what the issue is. While comparing with the calendar app ([example](https://github.com/nextcloud/calendar/blob/533ad83f0cd30532f77a772de04480a6262f078c/src/components/Editor/SaveButtons.vue#L28)) I found that the use double curly braces. I do not know enough of Vue to see if this is some Vue related Syntax or for the sake of the translation tool.

Let's see what comes out of it so far.

**Comment by mrzapp** [comment] 2020-06-14 12:59
@christianlupus yeah, the .js files are only generated in the release script. It might be that we have to version them, which would be odd, but doable. Thanks for looking into it

**Comment by christianlupus** [comment] 2020-06-16 06:48
I just saw that [a recent commit by the bot](https://github.com/mrzapp/nextcloud-cookbook/commit/c09638cbdab67a8d17a1ca160117489b41a9d713) seemed to have brought back the l10n files. I suspect this is related to #258 but I do not understand why it took 2 days to get there (vs. daily crawling).
To close this issue, you have to make a new release. Then things should be normal for now. We should however keep an eye on the commits of the bot to avoid surprises on the next release.

**Comment by MyKeySoftMK** [comment] 2020-06-20 17:15
I using 0.7.4 - and all my words are english - but I want to use "german" - can you make a new release that the actual german language should be published?

**Comment by mrzapp** [comment] 2020-06-23 07:01
Alright, I've published a new release with the l10n files. We can reopen this issue if needed. Thanks for the update @christianlupus

**Closed by mrzapp** 2020-06-23 07:01 UTC
Labels: bug, internationalisation
