### ISSUE TITLE
No navigation menu on the left on desktop and mobile version, all browsers.

### ISSUE THREAD

**Issue by RobRobM** [mrzapp/nextcloud-cookbook#260] opened 2020-06-13 09:30 UTC
**Description**
The navigation menu on the left side of the app is missing when viewing cookbook in the mobile view or desktop view when recipe takes up the majority of the window. Before when clicking on the 3 dashes (left top) the navigation menu would open showing "create recipe" "recipe url" and the categories. Now this is only visible when the window is big enough to display navigation menu and recipe. Now when I click the 3 dashes, I navigate to all recipe's
 
**Reproduction**
1. Go to cookbook app on mobile browser or desktop browser 
(2. Navigate to any recipe)
3. On desktop reduce with to only show recipe and navigation menu dissapears 
3. click on 3 dashes (top left)
4. See all recipes instead of navigation menu

**Expected behavior**

**Screenshots**

**Browser**
Which browser are you using?

Update: navigating to recipe to reproduce problem not necessary.

**Comment by funky123** [comment] 2020-06-14 10:04
Same issue, here. But using it via Desktop and Google Chrome it seems working fine.
Only at mobile i get the issues with the missing or not wirking menu on the left.

**Comment by mrzapp** [comment] 2020-06-14 13:32
It seems we're missing the AppNavigationToggle component, can you look into that @sam-19? I tried implementing it into the AppNavi, but it's not responding or even showing up in the DOM. It seems it's supposed to be an `<a>` element with class name "app-navigation-toggle", but I can't find a single mention of in the source code of other apps. :man_shrugging:

**Comment by mrzapp** [comment] 2020-06-14 13:33
Duplicate of #245, but this issue is more descriptive, so I'm keeping it

**Comment by sam-19** [comment] 2020-06-14 13:36
The class definitions that hide the navigation come from NC source styles, so I cannot touch those. It seems my implementation is missing something. This seemed like a priority to some people so I hade a _dirty hack_ to make it work for now. Will have to look into a proper solution later.

**Closed** 2020-06-14 13:41 UTC
Labels: bug

**Comment by RobRobM** [comment] 2020-06-16 08:47
Thanks, navigation is back.
