### ISSUE TITLE
"Error: This page doesn't exist"

### ISSUE THREAD

**Issue by CSchaefer70** [mrzapp/nextcloud-cookbook#220] opened 2020-05-13 13:02 UTC
Getting "Error: This page doesn't exist" when trying to access recipes in Cookbook after upgrade from v0.6.3 to v0.6.5.  (NextCloud Version = 17.0.3; php 7.3; shared hosted server)

Using default directory "/Recipes".

All the recipes are showing this. Access to app and the categories and even see the titles and thumbnails. But clicking on them gives the error (instead of the recipe).

"Rescan library" has no effect.  Downgrade back to v0.6.3 works.

**Comment by mrzapp** [comment] 2020-05-13 13:09
Duplicate of #219

**Closed by mrzapp** 2020-05-13 13:09 UTC
