### ISSUE TITLE
[Feature request] Adaptive number of serving

### ISSUE THREAD

**Issue by Mageti** [mrzapp/nextcloud-cookbook#271] opened 2020-06-18 16:26 UTC
Hello,
Thanks for this wonderful app, I use it everyday.
I'd like to make a feature request : could it be possible to change the number of servings (not when editing the recipe, but on the normal read-only page), and this change of serving would instantly update the proportions of each ingredient ?

Example : I have a recipe for 4 people, and in the recipe, their is 400g of flour. But today, I want to cook for 2 people. I could change the number of serving to 2, and the ingredient list is updated to 200g of flour, without having to modify the recipe, or do math (400->200 is easy, but 3/4th of 375g is more difficult by head :-) )

Do you think it could be possible ? thanks in advance

**Comment by mpfaff** [comment] 2020-06-21 19:20
I'd love to see this feature. It would need the measurements of the ingredients to be separate from their names though.

**Comment by mrzapp** [comment] 2020-06-23 06:57
Duplicate of #116

**Closed by mrzapp** 2020-06-23 06:57 UTC
