### ISSUE TITLE
Recipe form text fields silently remove slashes

### ISSUE THREAD

**Issue by SirAiedail** [mrzapp/nextcloud-cookbook#275] opened 2020-06-22 15:09 UTC
**Description**
All text fields in the recipe form silently remove slashes (`/`) after saving. Both from the read-only view and subsequent edits.

**Reproduction**
1. Create or edit a recipe
2. Enter `hello/world` into the description (or any other text field)
3. Save the recipe

**Expected behavior**
In both view mode and edit mode the description should show the text `hello/world`.

**Actual behavior**
The description shows `helloworld` in both modes.

**Browser**
- Firefox 77.0.1 (64-bit) on Windows 10
- Chromium 80.0.3987.132 (64-bit) on Windows 10
- Firefox 78.0b1 (64-bit) on Arch Linux

**Comment by SirAiedail** [comment] 2020-06-22 15:13
The same applies to backslash (`\`). While the backslash has much less use in everyday texts, it is still unexpected to see it removed.

**Comment by inklikeurine** [comment] 2020-06-22 23:53
I am also experiencing this issue after upgrading from 0.5 to 0.7

**Comment by mrzapp** [comment] 2020-06-23 06:46
Duplicate of #266

**Closed by mrzapp** 2020-06-23 06:46 UTC
Labels: bug
