### ISSUE TITLE
Share capabilities?

### ISSUE THREAD

**Issue by CSchaefer70** [mrzapp/nextcloud-cookbook#221] opened 2020-05-13 15:48 UTC
Loving your "Cookbook" app.

Perhaps I'm missing something, but, I would find a feature to share to other users useful.  Is there a way within the app?  I attached a screenshot illustrating placement for an active Share ICON that would make sense to me.  Also, maybe within the "Personal Settings", include "Cookbook" and allow a user/group list?

If you already have this feature and I'm simply slow please send me a quick link... thanks!!

My current workaround:
Currently I step out from you "Cookbook" into the "Files" area and share from the recipe folder... the end user then needs to move the files into their "Recipe Folder".  After refresh everything is fine within "Cookbook".  Still this seems unnecessary as the location of the other user app folder is known...

Anyway, thank you again for a wonderful app.  I would like to help... not a great programmer but if you need translations or artwork I may be of assistance?

<img width="852" alt="2020-05-13_11-31-46" src="https://user-images.githubusercontent.com/26978180/81834588-1fdf5700-950f-11ea-9b31-bbbad73d17bb.png">

**Comment by mrzapp** [comment] 2020-05-14 07:56
This is a duplicate of #120 

It's on the roadmap, but for now you can just specify your recipe folder as a shared one to share all recipes :)

**Closed by mrzapp** 2020-05-14 07:56 UTC
