### ISSUE TITLE
	OCP\Lock\LockedException: "Dokumente/Rezepte/Mozzarella-Hähnchen in Basilikum-Sahnesauce" is locked

### ISSUE THREAD

**Issue by xsus95** [mrzapp/nextcloud-cookbook#71] opened 2019-10-09 06:13 UTC
Rename a recipe works. But e.g. changing the description or adding an keyword is not possible.

**Comment by mrzapp** [comment] 2019-10-09 08:36
@xsus95 I can't seem to reproduce this. Supposedly, this would happen when trying to move a folder or file to the same location it's already in.

A few questions:
1. Do you have the latest v0.5.1 installed?
2. Does this happen with all recipes or just some, e.g. the ones with German characters?
3. Can you post the JSON of the recipe that's causing trouble?

**Comment by xsus95** [comment] 2019-10-09 08:46
1: Yes, v0.5.1 is installed
2. with all recipes
3: file attached
[Penne mit Hähnchen und Champignons.json.txt](https://github.com/mrzapp/nextcloud-cookbook/files/3706348/Penne.mit.Hahnchen.und.Champignons.json.txt)

I am the only user on the nextcloud at the moment. Therefore, I can say that there are no copy operations and move operations at the same time.

**Comment by nrgeen** [comment] 2019-10-09 10:58
I can confirm the problem. Yesterday I installed version 0.5.1. Not as an update, but as a clean installation. I can create recipes, but I can't edit them afterwards.
I also use the app in a German environment. The error appears in all recipes. There are no specific German letters in the names.

**Comment by poltrian** [comment] 2019-10-09 11:15
Me too No editing

nrgeen <notifications@github.com> schrieb am Mi., 9. Okt. 2019, 12:58:

**Comment by danielroehrig** [comment] 2019-10-09 11:24
Can confirm. If anyone could checkout the latest develop branch and see if the error persists, that would be great. I merged some changes to the way updating a recipe works, and it worked ... on my machine...

**Comment by mrzapp** [comment] 2019-10-09 11:57
@danielroehrig I checked out develop, and it works for me. This is what I tested:

- Creating a new recipe
- Changing a recipe's name and keywords
- Downloading a recipe
- Deleting a recipe

Is there anything else you want to fix up, or should we push your changes as v0.5.2?

**Comment by danielroehrig** [comment] 2019-10-09 12:00
@mrzapp Feel free to do that. We need automatic testing. I won't be able to work on it today, but maybe that's something I could do in the next couple of days. Just to prevent this kind of regressions.

Do you have a kanban board or similar, to see who's trying to do what?

**Comment by mrzapp** [comment] 2019-10-09 12:06
@danielroehrig we do now :) https://github.com/mrzapp/nextcloud-cookbook/projects/1

**Closed by mrzapp** 2019-10-09 12:06 UTC
Labels: bug
