### ISSUE TITLE
Recipes get duplicated

### ISSUE THREAD

**Issue by vfauth** [mrzapp/nextcloud-cookbook#149] opened 2020-02-10 11:59 UTC
When I open the app, all of my recipes appear twice. If I use "rescan my library", the duplicates disappear. However, they appear again some minutes later (maybe after one of the cron?).

Screenshot there: https://cloud.fauth.eu/s/xYREzBS4prHBNdJ/preview

The directories in /Recipes are not duplicated.

Cookbook 0.5.7 on NC 18.0.0.

**Comment by mrzapp** [comment] 2020-02-29 17:05
@vfauth I can't seem to replicate this. The only reason I can think of user related, as the recipes you see in the list should be unique for each user. Can you think of any reason why several user's recipe lists might appear to you? Do you have anything unusual set up in that department?

**Comment by vfauth** [comment] 2020-03-05 15:29
I share the whole folder with somebody, so it may be the cause, indeed. Is there a better way to share recipes?

**Comment by mrzapp** [comment] 2020-03-16 08:30
I also share my folder with someone, but I'm not seeing duplicate entries. Could you check out the latest version from the 0.6.0 branch and see if the issues persists there? Bear in mind that this branch is unstable code.

**Comment by Schlaubischlump** [comment] 2020-03-17 15:06
I get the same error from time to time. 
Maybe another issue is related to this one. If you choose "Uncategorized" in the sidebar on the left side all recipes will be displayed the amount of times the folder is shared. For example, I share my folder with 3 different people so each recipe appears 3 times, but is treated as one sidebar entry. Its a little bit hard to explain, maybe the attached image helps to understand the problem.

<img width="300" alt="Screenshot 2020-03-17 at 16 05 56" src="https://user-images.githubusercontent.com/15728815/76869861-3350a780-6869-11ea-8746-b5d3053bd6fe.png">

**Comment by mrzapp** [comment] 2020-03-18 14:49
I will put this issue on hold, since we can't reproduce it in the latest development code. Once v0.6.0 has been released, we can verify whether or not you guys are still experiencing it.

**Comment by michelludes** [comment] 2020-03-24 18:56
Same here. I just updated nextcloud to 18.03 und did a update for cookbook to 0.6.1.
After that, every receipt was double

**Comment by michelludes** [comment] 2020-03-26 08:36
I have now corrected the duplicate entries twice manually. Unfortunately they are always duplicated the next day.
is a really annoying bug.
Nextcloud 18.03 und Cookbook 0.6.1

**Comment by mrzapp** [comment] 2020-03-27 15:15
@vfauth @michelludes @Schlaubischlump this issue is a bit perplexing to me, because no one else seem to experience it, and I can't reproduce it myself.

Could you try creating a new user on your NextCloud instance and use the default recipe folder? Does the error still occur? If not, please try to change the setup until the error is back, that way we can track down why it happens.

**Comment by Schlaubischlump** [comment] 2020-03-27 15:30
I was able to reproduce the issue on the first try. I startet with a clean NextCloud Installation. Besides Group Folders and Cookbook I have no other apps installed. Steps to hopefully reproduce the issue:

1. Create two user accounts 
2. Create a shared `Recipes` folder which both users can access
3. Upload some recipes via the NextCloud file manager
4. Open Cookbook 
5. Every recipe appears twice

Rescanning the recipe folder fixes the issue. 

I will conduct more tests to see if the issue still reappears from time to time.

**Comment by mrzapp** [comment] 2020-03-27 15:32
@Schlaubischlump can you try this setup without group folders? That app has been having some issues lately.

**Comment by Schlaubischlump** [comment] 2020-03-27 15:52
I can't get it to work. How do I add the external storage correctly? I tried to choose `NextCloud` from the external storage option and paste in the URL of the NextCloud instance, which destroyed my test installation 😅 Do I have to include it via `local` or `webdav` ?

**Comment by mrzapp** [comment] 2020-03-29 08:17
@Schlaubischlump you're right, I can reproduce it now as well! Working on it

**Comment by Schlaubischlump** [comment] 2020-03-29 08:18
Great, let me know if I a can help

**Comment by michelludes** [comment] 2020-03-29 08:28
Great. I Just have Seen your question this morning. Sorry for late andere.
But now you've got it👍

Schlaubischlump <notifications@github.com> schrieb am So., 29. März 2020,
10:19:

**Comment by mrzapp** [comment] 2020-03-29 08:30
@Schlaubischlump I've committed a fix for this, could you check out the `master` branch to see if it's working for you?

**Comment by Schlaubischlump** [comment] 2020-03-29 09:37
The bug seems to be gone. But now I have another bug. When I create a recipe with User A, logout and back in with User B, I first have to rescan the library before the new recipe appears in the list... I don't really see how this new issue should be related to your fix, but the bug wasn't there before.

**Comment by mrzapp** [comment] 2020-03-29 12:41
@Schlaubischlump it will appear with the next rescan, which happens automatically every 5 minutes (or however long you set it to) - so that means this issue should be solved

**Closed by mrzapp** 2020-03-29 12:41 UTC
Labels: bug
