### ISSUE TITLE
BadMethodCallException: path needs to be relative to the system wide data folder and point to a user specific file

### ISSUE THREAD

**Issue by paulcalabro** [mrzapp/nextcloud-cookbook#55] opened 2019-09-10 17:17 UTC
Saw the following exception in my logs after the upgrade to v0.4.0:

> 

Error | index | BadMethodCallException: path needs to be relative to the system wide data folder and point to a user specific file/var/www/html/lib/private/Encryption/Keys/Storage.php - line 253:OC\Encryption\Util->getUidAndFilename("/cookbook/cache")/var/www/html/lib/private/Encryption/Keys/Storage.php - line 169:OC\Encryption\Keys\Storage->getFileKeyDir("", "/cookbook/cache")/var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php - line 306:OC\Encryption\Keys\Storage->deleteAllFileKeys("/cookbook/cache")<<closure>>OC\Files\Storage\Wrapper\Encryption->rmdir("cookbook/cache")/var/www/html/apps/files_trashbin/lib/Storage.php - line 177:call_user_func([ OC\Files\S ... "], "cookbook/cache")/var/www/html/apps/files_trashbin/lib/Storage.php - line 117:OCA\Files_Trashbin\Storage->doDelete("cookbook/cache", "rmdir")/var/www/html/custom_apps/files_accesscontrol/lib/StorageWrapper.php - line 84:OCA\Files_Trashbin\Storage->rmdir("cookbook/cache")/var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 92:OCA\FilesAccessControl\StorageWrapper->rmdir("cookbook/cache")/var/www/html/lib/private/Files/View.php - line 1160:OC\Files\Storage\Wrapper\Wrapper->rmdir("cookbook/cache")/var/www/html/lib/private/Files/View.php - line 349:OC\Files\View->basicOperation("rmdir", "/cookbook/cache", [ "delete"])/var/www/html/lib/private/Files/Node/Folder.php - line 342:OC\Files\View->rmdir("/cookbook/cache")/var/www/html/custom_apps/cookbook/lib/Service/RecipeService.php - line 504:OC\Files\Node\Folder->delete()/var/www/html/custom_apps/cookbook/lib/Controller/RecipeController.php - line 141:OCA\Cookbook\Service\RecipeService->rebuildSearchIndex()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 166:OCA\Cookbook\Controller\RecipeController->reindex()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Cookbook ... }}, "reindex")/var/www/html/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook ... }}, "reindex")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Cookbo ... r", "reindex", OC\AppFramew ... {}, { _route: "c ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "c ... "})/var/www/html/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { _route: "c ... "})/var/www/html/lib/base.php - line 975:OC\Route\Router->match("/apps/cookbook/reindex")/var/www/html/index.php - line 42:OC::handleRequest()

...the app seems to be working, however.

**Comment by mrzapp** [comment] 2019-09-10 21:43
OK, for some reason it was struggling to delete the cache folder. I just tried this on my own instance and can't reproduce it. Is this error recurring?

**Comment by paulcalabro** [comment] 2019-09-11 03:56
Yeah, actually I just upgraded to `v0.4.1` and got a similar error as well:

```
[index] Error: BadMethodCallException: path needs to be relative to the system wide data folder and point to a user specific file at <<closure>>

 0. /var/www/html/lib/private/Encryption/Keys/Storage.php line 253
    OC\Encryption\Util->getUidAndFilename("/cookbook/cache")
 1. /var/www/html/lib/private/Encryption/Keys/Storage.php line 169
    OC\Encryption\Keys\Storage->getFileKeyDir("", "/cookbook/cache")
 2. /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php line 306
    OC\Encryption\Keys\Storage->deleteAllFileKeys("/cookbook/cache")
 3. <<closure>>
    OC\Files\Storage\Wrapper\Encryption->rmdir("cookbook/cache")
 4. /var/www/html/apps/files_trashbin/lib/Storage.php line 177
    undefinedundefinedcall_user_func([OC\Files\Storag ... "], "cookbook/cache")
 5. /var/www/html/apps/files_trashbin/lib/Storage.php line 117
    OCA\Files_Trashbin\Storage->doDelete("cookbook/cache", "rmdir")
 6. /var/www/html/custom_apps/files_accesscontrol/lib/StorageWrapper.php line 84
    OCA\Files_Trashbin\Storage->rmdir("cookbook/cache")
 7. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 92
    OCA\FilesAccessControl\StorageWrapper->rmdir("cookbook/cache")
 8. /var/www/html/lib/private/Files/View.php line 1160
    OC\Files\Storage\Wrapper\Wrapper->rmdir("cookbook/cache")
 9. /var/www/html/lib/private/Files/View.php line 349
    OC\Files\View->basicOperation("rmdir", "/cookbook/cache", ["delete"])
10. /var/www/html/lib/private/Files/Node/Folder.php line 342
    OC\Files\View->rmdir("/cookbook/cache")
11. /var/www/html/custom_apps/cookbook/lib/Service/RecipeService.php line 504
    OC\Files\Node\Folder->delete()
12. /var/www/html/custom_apps/cookbook/lib/Controller/RecipeController.php line 141
    OCA\Cookbook\Service\RecipeService->rebuildSearchIndex()
13. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Cookbook\Controller\RecipeController->reindex()
14. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Cookbook\Con ... }}, "reindex")
15. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Cookbook\Con ... }}, "reindex")
16. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Cookbook\\ ... r", "reindex", OC\AppFramework\ ... {}, {_route: "cookbook.recipe.reindex"})
17. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "cookbook.recipe.reindex"})
18. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "cookbook.recipe.reindex"})
19. /var/www/html/lib/base.php line 975
    OC\Route\Router->match("/apps/cookbook/reindex")
20. /var/www/html/index.php line 42
    OC::handleRequest()

POST /apps/cookbook/reindex
from 8.39.233.94 by paulcalabro at 2019-09-11T03:52:58+00:00
```

Each time I have to click the rescan library button twice. 
The first time I get this error message "Could not rebuild recipe index." and the second time it seems to work and my recipes reappear.

**Comment by paulcalabro** [comment] 2019-09-11 04:15
The only thing I can think of that seems relevant is:

- At one point, I enabled encryption 
- I then disabled it
- I re-enabled encryption, but only for external storage (to avoid the performance penalty). And that's my current setup.

**Comment by mrzapp** [comment] 2019-09-11 07:26
Hm, no changes have been made to the storage logic since very early on. A wild guess is that, when removing cache, that the app is trying to remove a folder that's system-wide and not user-specific, and when encryption is enabled that's somehow frowned upon?

It seems to be a core issue, though, and I would have expected this to have been raised multiple times already, since it's not related to the latest changes.

As far as I can tell, although I might be wrong, there's little we can do about it. A related issue is discussed [here](https://github.com/nextcloud/groupfolders/issues/71)

Closing this issue for now, as it doesn't seem to be directly related to this app. If you manage to reliably track down the cause of the issue to an implementation in this app, we can reopen it.

**Closed by mrzapp** 2019-09-11 07:26 UTC
Labels: bug
