### ISSUE TITLE
App not working after upgrade

### ISSUE THREAD

**Issue by GutHib** [mrzapp/nextcloud-cookbook#276] opened 2020-06-22 21:36 UTC
Hi,

I had version 0.5x installed and upgraded to the newest 0.7x.

After the upgrade, clicking on the recipe thumbnails would tell me no recipes could be found. I then imported a recipe and tried to delete one (I only had three recipes in the database and was prepared to start from scratch) but that just produced more problems. Second time I tried, deleting a recipe did nothing, and clicking on one recipe brought up another one, but only part of it.

Then I logged out and back in, and now, when I try to open the cookbook app, I just get a blank screen with the Nextcloud toolbar. Deleted the app and reinstalled, but makes no difference.

UPDATE: If I'm not mistaken, the original problems were due to a change in the language settings done by the update script. Recipes were residing in a folder called "Recipes" - after moving them to the recipe folder in my local language, they are showing up again.

The problem with the white screen remains, but only in Edge browser (even after logging out and back in again). Other browsers are fine.

**Comment by mrzapp** [comment] 2020-06-23 06:53
Duplicate of #269

**Closed by mrzapp** 2020-06-23 06:53 UTC

**Comment by GutHib** [comment] 2020-06-23 09:23
Thanks for the quick response, hadn't seen the other thread. What about the second observation, that there's only a white screen in Edge browser?

**Comment by mrzapp** [comment] 2020-06-23 11:12
@GutHib not sure about that, since I've never used that browser. I recommend using a more standards friendly alternative, like Firefox :)
