### ISSUE TITLE
Support for fooby.ch and swissmilk.ch

### ISSUE THREAD

**Issue by MrReSc** [mrzapp/nextcloud-cookbook#211] opened 2020-04-30 15:01 UTC
Unfortunately, importing a recipe from [fooby.ch](url) and [swissmilk.ch](url) does not work correctly.
As far as I have seen, schema.org is supported, but I am not sure if this is true.

How can I find out if a website meets the requirements for the import to work?

- recipe from [fooby](https://fooby.ch/de/rezepte/19476/radiesli-flammkuchen?startAuto1=0)
- recipe from [swissmilk](https://www.swissmilk.ch/de/rezepte-kochideen/rezepte/LM200405_17/spargeln-im-ofen/?collection=97440&index=2)

**Comment by Teifun2** [comment] 2020-05-05 12:37
I just tested a fooby recipe but it seemed to me that it was more or less properly imported (some parts where lost).
Do you have more specific info on what is not working properly?

**Comment by mrzapp** [comment] 2020-05-05 13:00
@Teifun2 when importing the recipes mentioned, all I got was a list of ingredients that were actually instructions. The image downloaded fine, though.

Both `recipeIngredient` and `recipeInstructions` are present in the HTML, though, so the problem is probably with our parser.

**Comment by mrzapp** [comment] 2020-06-01 11:07
@MrReSc both of these sites will work properly in `v0.7.0`, which will be released soon.

The instructions from fooby.ch are still all in one step, but there's nothing we can/should do about that, as they are just using a rich text field with no meaningful markup that we could use to separate the steps with.

**Closed** 2020-06-07 06:00 UTC
Labels: website support

**Comment by MrReSc** [comment] 2020-06-09 05:32
> @MrReSc both of these sites will work properly in `v0.7.0`, which will be released soon.

@mrzapp  thanks for the fast processing.

> The instructions from fooby.ch are still all in one step, but there's nothing we can/should do about that, as they are just using a rich text field with no meaningful markup that we could use to separate the steps with.

The instruction is separated by the title `h3 tag` in HTML. From the context you can conclude that it is the instruction order.
Following is an example:

![Bildschirmfoto vom 2020-06-09 07-26-02](https://user-images.githubusercontent.com/24952268/84109407-e1ac5900-aa22-11ea-8c1c-1a6df3261615.png)

This is certainly not an elegant solution, but would work for fooby.

What I also noticed is that umlauts (äüö) are not imported correctly by fooby. When importing from swissmilk it works.

**Comment by mrzapp** [comment] 2020-06-09 07:40
@MrReSc that would only be the case for this one site, and we are not doing site specific parsers.

It's up to the recipe websites to follow schema.org standards. It would be a minor change for them to implement it properly, but a huge maintenance job for us to accommodate their sloppiness. Like, tomorrow they might change all their `h3` tags to `h4` tags, we just can't know.

I recommend contacting the site's staff about this issue, as fixing the markup would help them get better visibility in search engines too.

**Comment by MrReSc** [comment] 2020-07-29 14:38
When I import a recipe from swissmilk, there is a space between the quantity and the ingredient missing.
![grafik](https://user-images.githubusercontent.com/24952268/88814019-dfac7e00-d1b9-11ea-8ee2-67b3dbbb38f1.png)
