### ISSUE TITLE
Manually add recipes

### ISSUE THREAD

**Issue by lmitchel** [mrzapp/nextcloud-cookbook#10] opened 2019-06-26 04:30 UTC
I do not see any way to manually add a recipe.  Using Firefox and Chrome.  NextCloud Version 16.0.1.
![NextCloud-noaddbutton](https://user-images.githubusercontent.com/47064979/60150858-319cfc00-978f-11e9-8c8d-c7a97ebb6ed1.png)

After cheating by editing a file and changing the name, ingredients, and instructions a new .json file is created.

**Comment by amishtechie** [comment] 2019-07-08 03:59
This would be a great feature. Almost every recipe I try fails to import.

**Comment by mrzapp** [comment] 2019-07-11 11:11
@amishtechie A lot of recipe sites are unfortunately not implementing uischema.org correctly, which makes them hard to read automatically. If you want to help out with the parser, it's here: https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L213

**Comment by johanpalmqvist** [comment] 2019-07-11 11:21
There is an open bounty for this issue.

Bounty Source Link:
https://www.bountysource.com/issues/76058981-manually-add-recipes

**Comment by mrzapp** [comment] 2019-07-11 12:07
@johanpalmqvist no need for a bounty, the new release should fix this

**Comment by JimmyKater** [comment] 2019-10-08 11:10
v0.5.0 doesnt allow me still to manually add an receipe by my own. it tells me "couldn't update".

**Comment by poltrian** [comment] 2019-10-08 11:51
I can confirm

Am Dienstag, den 08.10.2019, 04:10 -0700 schrieb JimmyKater:

**Comment by mrzapp** [comment] 2019-10-08 12:18
Damn, that's a regression since the REST API was merged. I'm looking into it

**Comment by mrzapp** [comment] 2019-10-08 13:03
Seems to be a regression since the REST API was merged, I published v0.5.1 with a fix

**Closed by mrzapp** 2019-10-08 13:03 UTC
Labels: enhancement

**Comment by poltrian** [comment] 2019-10-08 13:46
Thanks again for greate work!
Am Dienstag, den 08.10.2019, 06:03 -0700 schrieb Jeppe Zapp:

**Comment by danielroehrig** [comment] 2019-10-08 19:22
Let me try and fix this regression (that I introduced) and still keep that REST endpoint.
