### ISSUE TITLE
Keywords are searched in the Titles of Recipes

### ISSUE THREAD

**Issue by Teifun2** [mrzapp/nextcloud-cookbook#117] opened 2019-12-05 13:19 UTC
I'm unsure if this is intentional or not so i ask.

When i have multiple Recipes with the word "best" (just an example) in them, but in no recipe exists a keyword "best" these recipes are not grouped together. 

As soon as i add the keyword "best" to any recipe (also those without best in their title) all recipes either with the keyword "best" or with "best" in the title are combined to one category.

Is this expected behavior? could this lead to weird associations?

**Comment by mrzapp** [comment] 2019-12-05 15:02
That seems like a bug. The category dropdown only parses keywords, not titles. Only the search field uses titles.

Just to be clear, the issue is that when you're using the category dropdown to filter the recipes, certain recipes show up that don't have the selected keyword in their keywords list?

**Comment by Teifun2** [comment] 2019-12-05 15:19
> Just to be clear, the issue is that when you're using the category dropdown to filter the recipes, certain recipes show up that don't have the selected keyword in their keywords list?

Yes exactly that happens.

**Comment by mrzapp** [comment] 2019-12-05 15:21
Alright, I've marked it as a bug, but since it's not critical, it can wait until 0.6.0

**Comment by mrzapp** [comment] 2020-03-16 08:49
Since the category dropdown will be phased out in 0.6.0, I'm closing this

**Closed by mrzapp** 2020-03-16 08:49 UTC
Labels: bug
